class String(value): ...
class Identifier(value): ...
class RegularExpression(value): ...
class Comment(message): ...
class Start(start_rule): ...
class Token(name, value): ...
class Production(parts): ...
class Rule(name, productions): ...
class Grammar(declarations): ...
